<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GTEVIFT" failures="0" tests="4" name="test runner-1" time="0.189" errors="0" timestamp="2023-08-07T16:53:25 IST">
  <testcase classname="com.crmGenericUtility.BaseClass" name="@BeforeSuite config_Bs" time="0.674">
    <failure type="java.sql.SQLException" message="Access denied for user &amp;apos;root&amp;apos;@&amp;apos;localhost&amp;apos; (using password: YES)">
      <![CDATA[java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
at com.crmGenericUtility.DataBaseUtility.connectToDB(DataBaseUtility.java:22)
at com.crmGenericUtility.BaseClass.config_Bs(BaseClass.java:31)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeSuite config_Bs -->
  <testcase classname="testng_Practice.TestNg_Batch_ExecuTest" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="testng_Practice.TestNg_Batch_ExecuTest" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testng_Practice.TestNG_Group_ExTest" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="testng_Practice.TestNG_Group_ExTest" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
</testsuite> <!-- test runner-1 -->
